version: '3'
services:
  netcore-https:
    build: .
    ports:
    - "8081:80"
    - "8082:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8082"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/